/* tslint:disable */
/* eslint-disable */
/**
 * API description
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTodoDto
 */
export interface CreateTodoDto {
    /**
     * 
     * @type {string}
     * @memberof CreateTodoDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTodoDto
     */
    content: string;
}

/**
 * Check if a given object implements the CreateTodoDto interface.
 */
export function instanceOfCreateTodoDto(value: object): value is CreateTodoDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateTodoDtoFromJSON(json: any): CreateTodoDto {
    return CreateTodoDtoFromJSONTyped(json, false);
}

export function CreateTodoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTodoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function CreateTodoDtoToJSON(json: any): CreateTodoDto {
    return CreateTodoDtoToJSONTyped(json, false);
}

export function CreateTodoDtoToJSONTyped(value?: CreateTodoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

