/* tslint:disable */
/* eslint-disable */
/**
 * API description
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoEntity } from './TodoEntity';
import {
    TodoEntityFromJSON,
    TodoEntityFromJSONTyped,
    TodoEntityToJSON,
    TodoEntityToJSONTyped,
} from './TodoEntity';

/**
 * 
 * @export
 * @interface FindTodoResponseDto
 */
export interface FindTodoResponseDto {
    /**
     * 
     * @type {TodoEntity}
     * @memberof FindTodoResponseDto
     */
    todo: TodoEntity;
}

/**
 * Check if a given object implements the FindTodoResponseDto interface.
 */
export function instanceOfFindTodoResponseDto(value: object): value is FindTodoResponseDto {
    if (!('todo' in value) || value['todo'] === undefined) return false;
    return true;
}

export function FindTodoResponseDtoFromJSON(json: any): FindTodoResponseDto {
    return FindTodoResponseDtoFromJSONTyped(json, false);
}

export function FindTodoResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindTodoResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'todo': TodoEntityFromJSON(json['todo']),
    };
}

export function FindTodoResponseDtoToJSON(json: any): FindTodoResponseDto {
    return FindTodoResponseDtoToJSONTyped(json, false);
}

export function FindTodoResponseDtoToJSONTyped(value?: FindTodoResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'todo': TodoEntityToJSON(value['todo']),
    };
}

