/* tslint:disable */
/* eslint-disable */
/**
 * API description
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoEntity } from './TodoEntity';
import {
    TodoEntityFromJSON,
    TodoEntityFromJSONTyped,
    TodoEntityToJSON,
    TodoEntityToJSONTyped,
} from './TodoEntity';

/**
 * 
 * @export
 * @interface FindTodoListResponseDto
 */
export interface FindTodoListResponseDto {
    /**
     * 
     * @type {Array<TodoEntity>}
     * @memberof FindTodoListResponseDto
     */
    todos: Array<TodoEntity>;
}

/**
 * Check if a given object implements the FindTodoListResponseDto interface.
 */
export function instanceOfFindTodoListResponseDto(value: object): value is FindTodoListResponseDto {
    if (!('todos' in value) || value['todos'] === undefined) return false;
    return true;
}

export function FindTodoListResponseDtoFromJSON(json: any): FindTodoListResponseDto {
    return FindTodoListResponseDtoFromJSONTyped(json, false);
}

export function FindTodoListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindTodoListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'todos': ((json['todos'] as Array<any>).map(TodoEntityFromJSON)),
    };
}

export function FindTodoListResponseDtoToJSON(json: any): FindTodoListResponseDto {
    return FindTodoListResponseDtoToJSONTyped(json, false);
}

export function FindTodoListResponseDtoToJSONTyped(value?: FindTodoListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'todos': ((value['todos'] as Array<any>).map(TodoEntityToJSON)),
    };
}

