/* tslint:disable */
/* eslint-disable */
/**
 * API description
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInUserDto
 */
export interface SignInUserDto {
    /**
     * 
     * @type {string}
     * @memberof SignInUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignInUserDto
     */
    password: string;
}

/**
 * Check if a given object implements the SignInUserDto interface.
 */
export function instanceOfSignInUserDto(value: object): value is SignInUserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignInUserDtoFromJSON(json: any): SignInUserDto {
    return SignInUserDtoFromJSONTyped(json, false);
}

export function SignInUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignInUserDtoToJSON(json: any): SignInUserDto {
    return SignInUserDtoToJSONTyped(json, false);
}

export function SignInUserDtoToJSONTyped(value?: SignInUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

