/* tslint:disable */
/* eslint-disable */
/**
 * API description
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpUserDto
 */
export interface SignUpUserDto {
    /**
     * 
     * @type {string}
     * @memberof SignUpUserDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpUserDto
     */
    password: string;
}

/**
 * Check if a given object implements the SignUpUserDto interface.
 */
export function instanceOfSignUpUserDto(value: object): value is SignUpUserDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignUpUserDtoFromJSON(json: any): SignUpUserDto {
    return SignUpUserDtoFromJSONTyped(json, false);
}

export function SignUpUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignUpUserDtoToJSON(json: any): SignUpUserDto {
    return SignUpUserDtoToJSONTyped(json, false);
}

export function SignUpUserDtoToJSONTyped(value?: SignUpUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

