/* tslint:disable */
/* eslint-disable */
/**
 * API description
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoEntity
 */
export interface TodoEntity {
    /**
     * 
     * @type {number}
     * @memberof TodoEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TodoEntity
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TodoEntity
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof TodoEntity
     */
    userId: string;
    /**
     * 
     * @type {Date}
     * @memberof TodoEntity
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TodoEntity
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the TodoEntity interface.
 */
export function instanceOfTodoEntity(value: object): value is TodoEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TodoEntityFromJSON(json: any): TodoEntity {
    return TodoEntityFromJSONTyped(json, false);
}

export function TodoEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'content': json['content'],
        'userId': json['userId'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function TodoEntityToJSON(json: any): TodoEntity {
    return TodoEntityToJSONTyped(json, false);
}

export function TodoEntityToJSONTyped(value?: TodoEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'userId': value['userId'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

