/* tslint:disable */
/* eslint-disable */
/**
 * API description
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTodoDto
 */
export interface UpdateTodoDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    content: string;
}

/**
 * Check if a given object implements the UpdateTodoDto interface.
 */
export function instanceOfUpdateTodoDto(value: object): value is UpdateTodoDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function UpdateTodoDtoFromJSON(json: any): UpdateTodoDto {
    return UpdateTodoDtoFromJSONTyped(json, false);
}

export function UpdateTodoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTodoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function UpdateTodoDtoToJSON(json: any): UpdateTodoDto {
    return UpdateTodoDtoToJSONTyped(json, false);
}

export function UpdateTodoDtoToJSONTyped(value?: UpdateTodoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

